## Random Values in Tensors

In [1]:
import tensorflow as tf

/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dty

#### a) Normal distribution

In [ ]:
# random_normal method signature
# tf. random.normal(shape, mean = 0, stddev =2, dtype=tf.float32, seed=None, name=None)

In [2]:
tf.random.normal(shape=(6, 5))

<tf.Tensor: id=5, shape=(6, 5), dtype=float32, numpy=
array([[-0.02405767, -0.19439186, -1.2731396 , -1.0606115 ,  0.03964252],
       [-2.0946667 , -0.8705545 , -0.25204065,  1.1264561 ,  0.27910334],
       [ 0.6033117 , -0.96702445, -0.2489363 , -0.3398405 , -0.95675874],
       [ 0.77230096, -0.19921932, -0.4895777 ,  0.48781127, -1.6763492 ],
       [-0.84879935,  1.6671357 , -0.993731  ,  0.65883124,  1.1263149 ],
       [-1.3980536 ,  0.62439394, -1.0402675 ,  0.416851  , -0.5588937 ]],
      dtype=float32)>

In [9]:
tf.random.normal(shape=(2, 4), mean=8, stddev=3.2)

<tf.Tensor: id=39, shape=(2, 4), dtype=float32, numpy=
array([[13.534141 ,  8.340326 ,  4.4566545, 10.289266 ],
       [ 4.7821364, 11.281537 ,  7.530502 ,  6.3387117]], dtype=float32)>

### b) Uniform Distribution

In [10]:
# random_uniform Method signature

# tf.random.uniform(shape, minval = 0, maxval= None, dtype=tf.float32, seed=None,  name=None)

In [11]:
tf.random.uniform(shape=(4, 2))

<tf.Tensor: id=47, shape=(4, 2), dtype=float32, numpy=
array([[0.05324423, 0.601568  ],
       [0.8631375 , 0.5368165 ],
       [0.5074129 , 0.989975  ],
       [0.47089398, 0.03002656]], dtype=float32)>

In [19]:
tf.random.uniform(shape=(3, 3), minval = 0, maxval= 10, seed=30)

<tf.Tensor: id=103, shape=(3, 3), dtype=float32, numpy=
array([[0.8456671, 9.556121 , 5.9912586],
       [2.2567463, 4.7012606, 9.8211565],
       [4.3512306, 9.002699 , 5.678537 ]], dtype=float32)>

In [ ]:
D

#### c) Seeding

In [24]:
tf.random.set_seed(2)

In [25]:
a = tf.random.uniform(shape=(3, 3), minval = 0, maxval= 10,dtype=tf.int32)
b = tf.random.uniform(shape=(3, 3), minval = 0, maxval= 10,dtype=tf.int32)

In [27]:
print(f"a: {a}\n")
print(f'b: {b}')

a: [[1 6 2]
 [7 3 6]
 [7 5 1]]

b: [[3 9 2]
 [8 6 1]
 [0 1 4]]


In [29]:
# Seed with same value (2)

tf.random.set_seed(2)

In [30]:
a1 = tf.random.uniform(shape=(3, 3), minval = 0, maxval= 10,dtype=tf.int32)
b1 = tf.random.uniform(shape=(3, 3), minval = 0, maxval= 10,dtype=tf.int32)

In [31]:
print(f"a1: {a1}\n")
print(f'b1: {b1}')

a1: [[1 6 2]
 [7 3 6]
 [7 5 1]]

b1: [[3 9 2]
 [8 6 1]
 [0 1 4]]
