## Largest and Smallest Elements

Finding indices of the elements with the largest or smallest values


In [1]:
import tensorflow as tf

/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/root/.virtualenvs/tfs/lib/python3.7/site-packages/tensorflow/python/framework/dty

 ##### method signatures

In [3]:
# Largest element's index

# tf.argmax(input, axis=None, name=None, output_type=tf.int64 )

In [4]:
# Smallest element's index

# tf.argmin(input, axis=None, name=None, output_type=tf.int64 )

In [6]:
a = tf.constant(tf.random.uniform(shape=(3, 3), minval=4, maxval=20, dtype=tf.int32))

In [29]:
print(a)
print('\nmax indices of a:\n')
print(tf.argmax(a)) # Max across rows

tf.Tensor(
[[ 8 19  6]
 [ 5 18 15]
 [12 17 10]], shape=(3, 3), dtype=int32)

max indices of a:

tf.Tensor([2 0 1], shape=(3,), dtype=int64)


In [8]:
# Max across columns
print(tf.argmax(a, axis=1))

tf.Tensor([1 1 1], shape=(3,), dtype=int64)


#### Index of minimum element

In [35]:

b = tf.constant(tf.random.uniform(shape=(4, 3), minval=0, maxval=20, dtype=tf.int32))

tf.Tensor(
[[15 16 14]
 [17 15  4]
 [ 2 10 13]
 [18  8 15]], shape=(4, 3), dtype=int32)
tf.Tensor([2 3 1], shape=(3,), dtype=int64)


In [40]:
print(f'b:\n {b}')


b:
 [[15 16 14]
 [17 15  4]
 [ 2 10 13]
 [18  8 15]]


In [37]:
# Min across rows
print(tf.argmin(b, axis=0))

tf.Tensor([2 3 1], shape=(3,), dtype=int64)


In [41]:
# Min across columns
print(tf.argmin(b, axis=1))

tf.Tensor([2 2 0 1], shape=(4,), dtype=int64)
