## Tensor Operations

In [3]:
import tensorflow as tf


#### Casting a tensor to numpy

In [8]:
t = tf.Variable([[5, 7, 3, 7], [8, 5 ,9, 4]], dtype=tf.float32)

In [15]:
t_np = t.numpy()
print(t_np)

[[5. 7. 3. 7.]
 [8. 5. 9. 4.]]


#### Finding the number of elements in a tensor

In [16]:
s = tf.size(input=t)
print(s.numpy())

8


#### Finding a tensor's datatype

In [17]:
# Datatype is specified by the dtype property
t.dtype

tf.float32

#### Broadcasting elements

In [18]:
t2 = t * 4
# print(t)
print(t2)

tf.Tensor(
[[20. 28. 12. 28.]
 [32. 20. 36. 16.]], shape=(2, 4), dtype=float32)


#### Casting 

In [19]:
tf_float = tf.Variable([46.2, 5.6, 54.3], dtype=tf.float32)
tf_int = tf.cast(tf_float, dtype=tf.int32)


In [20]:
tf_int

<tf.Tensor: id=48, shape=(3,), dtype=int32, numpy=array([46,  5, 54], dtype=int32)>

In [22]:
# With constants
four = tf.cast(tf.constant(4), dtype=tf.float32)
print(four)

tf.Tensor(4.0, shape=(), dtype=float32)
