## Random Values Example

### An example use case for random values

This example shows how to **initialize** a tf Variable from calling a random function.

It also shows how to **join related tensors** for convenience in accessing similar elements

In [2]:
import tensorflow as tf

In [24]:
scores = tf.Variable(tf.random.uniform(shape=(5, 1), maxval=10, dtype=tf.int32))

In [8]:
time = tf.Variable(tf.random.uniform(shape=(5, 1), minval=1, maxval=60, dtype=tf.int32))

In [12]:
reward = tf.abs(scores - time)

In [13]:
print(scores)
print(time)
print(reward)

<tf.Variable 'Variable:0' shape=(5, 1) dtype=int32, numpy=
array([[0],
       [1],
       [9],
       [3],
       [2]], dtype=int32)>
<tf.Variable 'Variable:0' shape=(5, 1) dtype=int32, numpy=
array([[24],
       [50],
       [34],
       [25],
       [ 8]], dtype=int32)>
tf.Tensor(
[[24]
 [49]
 [25]
 [22]
 [ 6]], shape=(5, 1), dtype=int32)


In [18]:
game_results = tf.concat(values=(scores, time, reward), axis=1)

In [19]:
print(game_results)

tf.Tensor(
[[ 0 24 24]
 [ 1 50 49]
 [ 9 34 25]
 [ 3 25 22]
 [ 2  8  6]], shape=(5, 3), dtype=int32)


In [22]:
# We can now access the reward and the time in took to make a certain score
# Example for the first score

score1 = game_results[0].numpy()

In [26]:
print(f'First Score: {score1[0]}\n')
print(f'Time taken:{score1[1]}, reward: {score1[2]}')

First Score: 0

Time taken:24, reward: 24
