## Largest and Smallest Elements

Finding indices of the elements with the largest or smallest values


In [2]:
import tensorflow as tf

 ##### method signatures

In [3]:
# Largest element's index

# tf.argmax(input, axis=None, name=None, output_type=tf.int64 )

In [4]:
# Smallest element's index

# tf.argmin(input, axis=None, name=None, output_type=tf.int64 )

In [6]:
a = tf.constant(tf.random.uniform(shape=(3, 3), minval=4, maxval=20, dtype=tf.int32))

In [29]:
print(a)
print('\nmax indices of a:\n')
print(tf.argmax(a)) # Max across rows

tf.Tensor(
[[ 8 19  6]
 [ 5 18 15]
 [12 17 10]], shape=(3, 3), dtype=int32)

max indices of a:

tf.Tensor([2 0 1], shape=(3,), dtype=int64)


In [8]:
# Max across columns
print(tf.argmax(a, axis=1))

tf.Tensor([1 1 1], shape=(3,), dtype=int64)


#### Index of minimum element

In [35]:

b = tf.constant(tf.random.uniform(shape=(4, 3), minval=0, maxval=20, dtype=tf.int32))

tf.Tensor(
[[15 16 14]
 [17 15  4]
 [ 2 10 13]
 [18  8 15]], shape=(4, 3), dtype=int32)
tf.Tensor([2 3 1], shape=(3,), dtype=int64)


In [40]:
print(f'b:\n {b}')


b:
 [[15 16 14]
 [17 15  4]
 [ 2 10 13]
 [18  8 15]]


In [37]:
# Min across rows

print(tf.argmin(b, axis=0))

tf.Tensor([2 3 1], shape=(3,), dtype=int64)


In [41]:
# Min across columns

print(tf.argmin(b, axis=1))

tf.Tensor([2 2 0 1], shape=(4,), dtype=int64)


### Max and Min elements

In [48]:
print('Maximum element of b')

tf.reduce_max(b).numpy()


Maximum element of b


18

In [49]:
print('Minimum element of b')
tf.reduce_min(b).numpy()

Minimum element of b


2